### ISSUE TITLE
Ужасный селфбот.

### ISSUE THREAD

**Issue by Its-MatriX** [Its-LALOL/Discord-Selfbot#1]
Не скачивайте этого селфбота. Этот человек очень высокого мнения о своём селфботе, и код нечитабельный!

Если всё же решите скачивать это, проверьте этот код на наличие токен грабберов.

https://github.com/Its-MatriX/Selfbot - гораздо лучше, и функций в скором времени будет больше, чем тут.

**Comment by Its-LALOL** [comment]
бедни, украл все функции с моего селфбота и еще говоришь не скачивать моего. Код читать вам не обязательно. Грабберов в моём селфботе нету. Мой селфбот гораздо лучше матрикса.

**Comment by Its-MatriX** [comment]
Уже нет. Скоро функций будет больше, и я потом ещё спрошу. И у тебя код нечитабельный. Когда я читал код, у мены лопнули глаза. И научись грамотно писать

**Comment by Its-LALOL** [comment]
В данный момент мой селфбот красивее и функциональней. Код как я уже говорил читать не обязательно, главное что селфбот работает. и вабщета писать грамммматна я умею!!!!!!!!!!!

**Comment by Its-MatriX** [comment]
Пон
